### ISSUE TITLE
Don't render loading and error events in provider

### ISSUE THREAD

**Issue by pors** [hussy-io/react-web3-provider#1]
Hi! I was just about to create something similar when I found your repo, great work!

I have a request: I think the provider would be easier to use when it always returns the wrapped component regardless if it is still loading or if a connection error has occurred. Users might want to render the feedback somewhere else in the page.

So the `loading` and `error` props will then become callback functions that don't return a component, and `Web3Provider` will always return the `Web3Context.Provider` with children.

If you agree I could give it a shot to create a PR, but I can't build the package, I get:

```
$ npm run build

> react-web3-provider@0.0.8 build /Users/mark/dev/temp/react-web3-provider
> babel src --presets babel-preset-es2015 --out-dir dist

SyntaxError: src/index.js: Unexpected token (56:10)
  54 |       } else {
  55 |         return (
> 56 |           <Web3Context.Provider value={this.state.web3}>
     |           ^
  57 |             {this.props.children}
  58 |           </Web3Context.Provider>
  59 |         );
```

I tried with node 6 and 9.

**Comment by petertulala** [comment]
Good suggestion. I've added this feature in 64bcd39d0fd8f677900c6be21e8800222b43fbd0.

Regarding your building error, I was not able to reproduce it with the latest node version.

**Comment by pors** [comment]
Thanks a lot!
